-- ============================================================
-- whatsapp_messages — memoria das mensagens capturadas do WhatsApp
-- Video: WhatsApp -> Supabase Edge Function -> agente
-- Banco: Supabase / Postgres
-- ============================================================
-- Como usar: cole tudo no SQL Editor do Supabase e rode.
-- Pode rodar mais de uma vez: usa "if not exists" onde importa.
-- ============================================================

create table if not exists public.whatsapp_messages (
  id bigint generated by default as identity not null,
  whatsapp_owner text not null,
  chat_type text not null,
  chat_id text null,
  chat_name text null,
  contact_phone text null,
  sender_phone text not null,
  sender_name text null,
  recipient_phone text null,
  direction text not null,
  message_type text not null default 'text'::text,
  message text null,
  caption text null,
  media_url text null,
  media_mime_type text null,
  media_file_name text null,
  media_sha256 text null,
  media_size_bytes bigint null,
  transcription text null,
  message_id text not null,
  external_message_id text null,
  reply_to_message_id text null,
  forwarded boolean null default false,
  is_edited boolean null default false,
  reaction text null,
  reacted_to_message_id text null,
  status text not null default 'sent'::text,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  message_created_at timestamp with time zone not null default now(),
  status_updated_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint whatsapp_messages_pkey primary key (id),
  constraint whatsapp_messages_message_id_key unique (message_id),
  constraint whatsapp_messages_chat_type_check check (chat_type in ('private', 'group')),
  constraint whatsapp_messages_direction_check check (direction in ('inbound', 'outbound')),
  constraint whatsapp_messages_status_check check (status in ('pending', 'sent', 'delivered', 'read', 'failed'))
);

create index if not exists idx_wa_messages_direction
  on public.whatsapp_messages (direction);

create index if not exists idx_wa_messages_contact_phone
  on public.whatsapp_messages (contact_phone);

create index if not exists idx_wa_messages_chat_id
  on public.whatsapp_messages (chat_id);

create index if not exists idx_wa_messages_message_created_at
  on public.whatsapp_messages (message_created_at desc);

create index if not exists idx_wa_messages_contact_recent
  on public.whatsapp_messages (contact_phone, message_created_at desc);

create index if not exists idx_wa_messages_owner
  on public.whatsapp_messages (whatsapp_owner);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_wa_messages_updated_at on public.whatsapp_messages;
create trigger trg_wa_messages_updated_at
  before update on public.whatsapp_messages
  for each row
  execute function public.set_updated_at();

-- RLS ligado e sem policy publica.
-- A Edge Function escreve com SERVICE_ROLE no servidor, entao ignora RLS.
-- Cliente/anon nunca deve escrever direto nesta tabela.
alter table public.whatsapp_messages enable row level security;
